# Shailendra Singh

In [1]:
import pandas as pd
import numpy as np

In [2]:
url='https://raw.githubusercontent.com/AdiPersonalWorks/Random/master/student_scores%20-%20student_scores.csv'
df=pd.read_csv(url)

In [3]:
df

Hours  Scores
0     2.5      21
1     5.1      47
2     3.2      27
3     8.5      75
4     3.5      30
5     1.5      20
6     9.2      88
7     5.5      60
8     8.3      81
9     2.7      25
10    7.7      85
11    5.9      62
12    4.5      41
13    3.3      42
14    1.1      17
15    8.9      95
16    2.5      30
17    1.9      24
18    6.1      67
19    7.4      69
20    2.7      30
21    4.8      54
22    3.8      35
23    6.9      76
24    7.8      86

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

array=df.values

X=array[:,0:1]
Y=array[:,-1]

In [5]:
X

array([[2.5],
       [5.1],
       [3.2],
       [8.5],
       [3.5],
       [1.5],
       [9.2],
       [5.5],
       [8.3],
       [2.7],
       [7.7],
       [5.9],
       [4.5],
       [3.3],
       [1.1],
       [8.9],
       [2.5],
       [1.9],
       [6.1],
       [7.4],
       [2.7],
       [4.8],
       [3.8],
       [6.9],
       [7.8]])

In [6]:
Y.reshape(-1,1)

array([[21.],
       [47.],
       [27.],
       [75.],
       [30.],
       [20.],
       [88.],
       [60.],
       [81.],
       [25.],
       [85.],
       [62.],
       [41.],
       [42.],
       [17.],
       [95.],
       [30.],
       [24.],
       [67.],
       [69.],
       [30.],
       [54.],
       [35.],
       [76.],
       [86.]])

In [7]:
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.3,random_state=0)

In [8]:
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [9]:
pred=model.predict(x_test)
pred

array([17.05366541, 33.69422878, 74.80620886, 26.8422321 , 60.12335883,
       39.56736879, 20.96909209, 78.72163554])

In [10]:
compare= {'Actual' : y_test, 'Predicted' : pred}
pd.DataFrame(compare)

Actual  Predicted
0    20.0  17.053665
1    27.0  33.694229
2    69.0  74.806209
3    30.0  26.842232
4    62.0  60.123359
5    35.0  39.567369
6    24.0  20.969092
7    86.0  78.721636

In [11]:
model.predict([[9.5]]) #Random prediction

array([95.36219891])

In [12]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, pred)

22.96509721270044

In [13]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, pred)

4.4197278080276545